[package]
name = "jaq"
group = "infinyon"
version = "0.1.0"
apiVersion = "0.1.0"
description = "JSON to JSON transformation using JQ"
license = "Apache-2.0"
visibility = "public"
repository = "https://github.com/infinyon/fluvio-jaq"

[[params]]
name = "filter"
description = "JQ filter to apply"
optional = false
