name: Publish crates to crates.io

on:
  workflow_dispatch:


env:
    WASI_TARGET: wasm32-wasip1
    FLUVIO_URL: https://hub.infinyon.cloud/install/install.sh
    FLUVIO_CHANNEL: stable


jobs:
  
  build:
    name: Build Smartmodule
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust ${{ matrix.rust }} toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit }}

      - name: Install FVM and Fluvio
        timeout-minutes: 10
        run: |
            curl -fsS ${{ env.FLUVIO_URL }} | bash
            echo "$HOME/.fvm/bin" >> $GITHUB_PATH
            echo "$HOME/.fluvio/bin" >> $GITHUB_PATH

      
      - name: Build Smartmodule
        run: make build

      - name: Login to Fluvio Cloud
        run: fluvio cloud login --email "${{ secrets.ORG_HUB_SA_NAME }}" \
          --password "${{ secrets.ORG_HUB_SA_PASSWD_PROD }}" \

      - name: Publish Smartmodule to Fluvio Cloud
        run: |
          smdk publish --public-yes
  